

logging.level.org.hibernate.orm.jdbc.bind=TRACE

spring.jackson.time-zone=Asia/Calcutta


spring.datasource.url=jdbc:mysql://gondola.proxy.rlwy.net:30380/railway
spring.datasource.username=root
spring.datasource.password=shNhxwZCdXavrCljtPuyGBDuUbvtmIsm
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
server.port=8080




spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=errirajinierrirajini@gmail.com
spring.mail.password=cuxgrqpxtwawzdwa
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true




server.address=0.0.0.0



spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest